CREATE DATABASE db_empl;

use db_empl;

CREATE TABLE T_OFFICES(
	OFFC_ID INT NOT NULL,
    OFFC_COUNTRY varchar(30) NOT NULL,
    OFFC_DESCRIPTION varchar(80) NOT NULL,
    OFFC_NAME varchar(30)
);

DROP TABLE T_OFFICES;

CREATE TABLE T_OFFICES(
	OFFC_ID INT NOT NULL,
    OFFC_COUNTRY varchar(30) NOT NULL,
    OFFC_DESCRIPTION varchar(90) NOT NULL,
    OFFC_NAME varchar(30)
);

ALTER TABLE T_OFFICES
	DROP column OFFC_NAME;

ALTER TABLE T_OFFICES
	ADD COLUMN
    OFFC_CITY varchar(50) NOT NULL
    AFTER OFFC_COUNTRY;

ALTER TABLE T_OFFICES
	CHANGE COLUMN OFFC_DESCRIPTION
    OFFC_DESCRIPTION varchar(100);

DESC T_OFFICES;

INSERT INTO T_OFFICES
	VALUES (10, 'España','Madrid', 'Oficina central');

INSERT INTO T_OFFICES
	VALUES (11, 'España','Barcelona', null);


INSERT INTO T_OFFICES
	VALUES (20, 'Chile','Santiago', 'Oficina principal de Chile'),
    (30, 'Argentina', 'Buenos aires',null);
    
SELECT OFFC_ID, OFFC_COUNTRY, OFFC_CITY 
	FROM T_OFFICES
    WHERE OFFC_DESCRIPTION LIKE '%Oficina%';
    
UPDATE T_OFFICES
	SET
		OFFC_CITY = 'Buenos Aires'
	WHERE
		OFFC_ID = 30;
        
CREATE TABLE T_KNOWLEDGE_LINES(
	KNLN_ID INT(11) NOT NULL,
    KNLN_NAME varchar(45) not null,
    primary key(KNLN_ID)
);

INSERT INTO T_KNOWLEDGE_LINES
	VALUES (10,'Java');
    
INSERT INTO T_KNOWLEDGE_LINES
	VALUES (20,'.Net');
    
INSERT INTO T_KNOWLEDGE_LINES
	VALUES (30,'Mainframe');

ALTER TABLE T_OFFICES
	ADD primary key(OFFC_ID);
    
CREATE TABLE T_EMPLOYEES(
	EMPL_ID INT NOT NULL AUTO_INCREMENT,
    OFFC_ID INT NOT NULL,
    KNLN_ID INT,
    EMPL_FORNAME VARCHAR(50) NOT NULL,
    EMPL_MIDDLE_NAME VARCHAR(50),
    EMPL_SURNAME VARCHAR(50) NOT NULL,
    EMPL_NUMBER INT NOT NULL,
    EMPL_HIRE_DATE DATETIME NOT NULL,
    EMPL_MENTOR_ID INT,
    PRIMARY KEY(EMPL_ID)
);  

INSERT INTO T_EMPLOYEES
	(OFFC_ID,KNLN_ID,EMPL_FORNAME,
    EMPL_SURNAME,EMPL_NUMBER,EMPL_HIRE_DATE)
    VALUES
    (10,10,'Juan','Perez',150,'2005-04-15');
    
INSERT INTO T_EMPLOYEES
	(OFFC_ID,KNLN_ID,EMPL_FORNAME,
    EMPL_SURNAME,EMPL_NUMBER,EMPL_HIRE_DATE, 
    EMPL_MENTOR_ID)
    VALUES
    (11,20,'Luis','Gonzalez',160,'2006-05-18', 1);

INSERT INTO T_EMPLOYEES
	(OFFC_ID,EMPL_FORNAME,
    EMPL_SURNAME,EMPL_NUMBER,EMPL_HIRE_DATE)
    VALUES
    (20,'Pedro','Garcia',180,'2006-05-18');

CREATE TABLE T_PROJECTS (
  PRJT_ID INT NOT NULL  AUTO_INCREMENT,
  PRJT_CODE VARCHAR(16) NOT NULL,
  PRJT_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (PRJT_ID));

CREATE TABLE T_PROJECTS_EMPLOYEES (
  PRJT_ID INT NOT NULL,
  EMPL_ID INT NOT NULL,
  PRIMARY KEY (PRJT_ID,EMPL_ID));

INSERT INTO T_PROJECTS
	(PRJT_CODE, PRJT_NAME)
	VALUES
	('EXT-001000-01234','Gestion de usuarios'),
    ('INT-001000-03200','Cursos de formacion');

INSERT INTO T_PROJECTS_EMPLOYEES
	VALUES
		(1,1), (2,1), (1,2);

ALTER TABLE T_EMPLOYEES 
    ADD INDEX FK_EMPL_OFFC (OFFC_ID), 
    ADD CONSTRAINT FK_EMPL_OFFC 
        FOREIGN KEY (OFFC_ID) 
        REFERENCES T_OFFICES (OFFC_ID);

ALTER TABLE T_EMPLOYEES 
    ADD INDEX FK_EMPL_KNLN (KNLN_ID), 
    ADD CONSTRAINT FK_EMPL_KNLN 
        FOREIGN KEY (KNLN_ID) 
        REFERENCES T_KNOWLEDGE_LINES (KNLN_ID);

UPDATE T_EMPLOYEES
	SET OFFC_ID = 40
    WHERE EMPL_FORNAME='Juan' AND EMPL_SURNAME='Perez';
    
DELETE FROM T_OFFICES
		WHERE OFFC_ID=10;
        
ALTER TABLE T_PROJECTS_EMPLOYEES
	ADD INDEX FK_PREMM_PRJT(PRJT_ID),
    ADD CONSTRAINT FK_PREM_PRJT
		FOREIGN KEY(PRJT_ID)
        references T_PROJECTS(PRJT_ID);

ALTER TABLE T_PROJECTS_EMPLOYEES
	ADD INDEX FK_PREMM_EMPL(EMPL_ID),
    ADD CONSTRAINT FK_PREM_EMPL
		FOREIGN KEY(EMPL_ID)
        references T_EMPLOYEES(EMPL_ID);
        
use db_empl;

SELECT e.EMPL_FORNAME, e.EMPL_SURNAME, 
	o.OFFC_CITY, k.KNLN_NAME
    from T_EMPLOYEES e
    INNER JOIN T_OFFICES o
    ON e.OFFC_ID = o.OFFC_ID
    LEFT OUTER JOIN T_KNOWLEDGE_LINES k
		ON e.KNLN_ID = k.KNLN_ID
    WHERE o.OFFC_COUNTRY IN ('España','Chile')
    AND e.EMPL_MENTOR_ID is null;
 
SELECT p.PRJT_CODE, p.PRJT_NAME, e.EMPL_NUMBER, e.EMPL_SURNAME
	FROM T_PROJECTS p
	inner join T_PROJECTS_EMPLOYEES pe
		ON p.PRJT_ID = pe.PRJT_ID
    inner join T_EMPLOYEES e
		ON pe.EMPL_ID = e.EMPL_ID
    WHERE e.EMPL_FORNAME = 'Juan';    

select e.EMPL_FORNAME, e.EMPL_SURNAME, k.KNLN_NAME
	from T_EMPLOYEES e
    inner join T_KNOWLEDGE_LINES k
    ON e.KNLN_ID = k.KNLN_ID;

select e.EMPL_FORNAME, e.EMPL_SURNAME, k.KNLN_NAME
	from T_EMPLOYEES e
    right outer join T_KNOWLEDGE_LINES k
    ON e.KNLN_ID = k.KNLN_ID;
    
select e.EMPL_FORNAME, e.EMPL_SURNAME, k.KNLN_NAME
	from T_EMPLOYEES e
    left outer join T_KNOWLEDGE_LINES k
    ON e.KNLN_ID = k.KNLN_ID;


CREATE VIEW V_PROJECTS_EMPLOYEES
	(PRJT_CODE, PRJT_NAME, EMPL_NUMBER, EMPL_FORNAME, EMPL_SURNAME  )
AS
SELECT p.PRJT_CODE, p.PRJT_NAME, e.EMPL_NUMBER, e.EMPL_FORNAME, e.EMPL_SURNAME
	FROM T_PROJECTS p
	inner join T_PROJECTS_EMPLOYEES pe
		ON p.PRJT_ID = pe.PRJT_ID
    inner join T_EMPLOYEES e
		ON pe.EMPL_ID = e.EMPL_ID;

SELECT * FROM V_PROJECTS_EMPLOYEES
WHERE PRJT_CODE LIKE 'EXT%';

CREATE TABLE T_DOCUMENTS (
  DOCS_ID INT NOT NULL AUTO_INCREMENT,
  EMPL_ID INT NOT NULL,
  DOCS_NAME VARCHAR(100) NOT NULL,
  DOCS_TYPE VARCHAR(50) NOT NULL,
  PRIMARY KEY (DOCS_ID));

ALTER TABLE T_DOCUMENTS ADD INDEX FK_DOCS_EMPL (EMPL_ID), 
    ADD CONSTRAINT FK_DOCS_EMPL 
        FOREIGN KEY (EMPL_ID) REFERENCES T_EMPLOYEES (EMPL_ID);

ALTER TABLE T_DOCUMENTS 
  ADD CONSTRAINT CT_CK_DOCS_TYPE 
  CHECK (DOCS_TYPE IN ('PDF', 'DOC', 'XLS'));

INSERT INTO T_DOCUMENTS
(EMPL_ID, DOCS_NAME, DOCS_TYPE)
VALUES
(1, 'Titulo', 'PDF'),
(1, 'Curriculum', 'DOC'),
(1, 'Certificado OCP', 'PDF'),
(1, 'Matriz conocimientos', 'XLS'),
(2, 'Grado', 'PDF'),
(2, 'Curriculum', 'DOC'),
(2, 'Certificado MS', 'PDF'),
(3, 'Titulo', 'PDF');

SELECT CONCAT(e.EMPL_FORNAME, ' ',e.EMPL_SURNAME) FULL_NAME,
	count(d.DOCS_ID) NUM_DOCS
    from T_EMPLOYEES e
    inner join T_DOCUMENTS d
    on e.empl_id = d.EMPL_ID
    group by FULL_NAME;

SELECT CONCAT(e.EMPL_FORNAME, ' ',e.EMPL_SURNAME) FULL_NAME,
	count(d.DOCS_ID) NUM_DOCS
    from T_EMPLOYEES e
    inner join T_DOCUMENTS d
    on e.empl_id = d.EMPL_ID
    group by FULL_NAME
    order by NUM_DOCS ASC;
    
SELECT CONCAT(e.EMPL_FORNAME, ' ',e.EMPL_SURNAME) FULL_NAME,
	count(d.DOCS_ID) NUM_DOCS
    from T_EMPLOYEES e
    inner join T_DOCUMENTS d
    on e.empl_id = d.EMPL_ID
    group by FULL_NAME
    order by NUM_DOCS ASC limit 1,2;
    
    
    
    
    
    



        
    
    
    
    
    
    
    


